#!/bin/bash
    
    webadd1="http://helpdesk.wi-tribe.net.pk:8080/secure/BrowseProjects.jspa";
    webadd2="http://helpdesk.wi-tribe.net.pk:8080/logout.jsp";
    search="Satyam BRM Project";
    page=`echo $webadd1 |cut -d "/" -f 1`;
    base=/home/amir/scripts/weblogin/helpdesk;
    
    rm -Rf $base/* #2>/dev/null;
    cd $base;
    
    wget -q --tries 1 --timeout 20 --save-cookies cookies.txt --post-data 'os_username=amir.aziz&os_password=errorcode406&os_cookie=true' $webadd1;
    if [ -f $base/BrowseProjects.jspa ]
    then
	grep "$search" $base/BrowseProjects.jspa >> /dev/null;
	if [ $? -eq 0 ]
	then
	    echo 1;
	else
    	    echo 0;
	fi
    else
	echo 0;
    fi
    wget -q --load-cookies cookies.txt -p $webadd2;
