#!/bin/bash
    
    webadd1="http://10.1.82.26:8082/PInfranetServlet?login=TestAcc340&password=test1&service=ip&page=login_verify&sessionState=start&Component=com.portal.web.comp.PLoginBeanImpl";
    webadd2="http://10.1.82.26:8082/PInfranetServlet?page=logout&sessionState=end"
    search="Mr. Amir aziz";
    page=`echo $webadd1 |cut -d "/" -f 1`;
    base=/home/amir/scripts/weblogin/payngo;
    
    rm -Rf $base/*;
    cd $base;
    
    wget -q --tries 1 --timeout 20 --save-cookies cookies.txt "$webadd1" --output-document=$base/myProfile.jsp;
#
#    if [ -f $base/myProfile.jsp ]
#    then
#	grep "$search" $base/myProfile.jsp >> /dev/null;
#	if [ $? -eq 0 ]
#	then
#	    echo 1;
#	else
#    	    echo 0;
#	fi
#    else
#	echo 0;
#    fi
    wget -q --load-cookies cookies.txt "$webadd2";
