#!/bin/bash
    
    webadd1="http://smarts.wi-tribe.net.pk/vims/login.php";
    webadd2="http://smarts.wi-tribe.net.pk/vims/logout.php";
    search="Check Voucher Current Status";
    page=`echo $webadd1 |cut -d "/" -f 1`;
    base=/home/amir/scripts/weblogin/smarts;
    
    rm -Rf $base/* #2>/dev/null;
    cd $base;
    
    wget -q --tries 1 --timeout 20 --save-cookies cookies.txt --post-data 'username=billingadmin&password=billingadmin' $webadd1;
    if [ -f $base/index.php ]
    then
	grep "$search" $base/index.php >> /dev/null;
	if [ $? -eq 0 ]
	then
	    echo 1;
	else
    	    echo 0;
	fi
    else
	echo 0;
    fi
    wget -q --load-cookies cookies.txt -p $webadd2;
