<?php

define( USER_ROLES_T,		'CFG_USER_ROLES');
define( USER_TEAMS_T,		'CFG_USER_TEAMS'); 
define( USER_T,			'USERS');

define( VIMS_REFIX,	'VIMS_');
define( CHANNEL_T,				VIMS_REFIX.'CHANNEL');
define( CHANNEL_TYPE_T,			VIMS_REFIX.'CHANNEL_TYPE');
define( ITEM_INFO_T,			VIMS_REFIX.'ITEM_INFORMATION');
define( ORDER_T,				VIMS_REFIX.'ORDER');
define( ORDER_ITEM_T,			VIMS_REFIX.'ORDER_ITEMS');
define( ORDER_STATE_T,			VIMS_REFIX.'ORDER_STATE');
define( ORDER_STATUS_T,			VIMS_REFIX.'ORDER_STATUS');
define( ORDER_TYPE_T,			VIMS_REFIX.'ORDER_TYPE');
define( PROV_LOG_T,				VIMS_REFIX.'PROVISIONING_LOG');
define( REPLACEMENT_T,			VIMS_REFIX.'REPLACEMENT');
define( REPLACEMENT_OVERIDE_T,			VIMS_REFIX.'REP_OVERRIDE');
define( TRACKER_T,				VIMS_REFIX.'TRACKER');
define( TRANSFER_TYPE_T,		VIMS_REFIX.'TRANSFER_TYPE');
define( COMMISSION_T,		VIMS_REFIX.'COMMISSION_RULES');
define(LOCATIONS_HIE_T, VIMS_REFIX.'LOCATIONS_HIERARCHY');
define(GEOTYPE_T, VIMS_REFIX.'GEO_TYPES');
define(DISCOUNT_T,VIMS_REFIX.'DISCOUNT_RULES');
define(DISCOUNT_TYPE_T,VIMS_REFIX.'DISCOUNT_TYPES');
define(INVOICE_T,VIMS_REFIX.'INVOICE');
define(INVOICE_ORDER_T,VIMS_REFIX.'INVOICE_ORDER');
define(RENTAL_RULE_T,VIMS_REFIX.'RENTAL_RULES');
define(RENTAL_T,VIMS_REFIX.'RENTAL');

?>